ccflags-y += -I$(src)/../include

obj-m     += allegro.o

allegro-objs := \
		al_alloc.o \
		al_char.o \
		al_codec.o \
		al_list.o \
		al_mail.o \
		al_mailbox.o \
		al_queue.o \
		al_test.o \
		al_user.o \
		al_vcu.o \
		mcu_interface.o \
		mcu_utils.o \

